name: Regular base image update check
#   SOURCE: https://www.flypenguin.de/2021/07/30/auto-rebuild-docker-images-if-base-image-changes-using-github-actions/

on:
  push:
    branches: [ main ]
  schedule:
    - cron: "23 13 3 * *"

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Docker Image Update Checker
        id: baseupdatecheck
        uses: lucacome/docker-image-update-checker@v1.1.0
        with:
          base-image: library/caddy:alpine
          image: cryorig/caddycf

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        if: steps.baseupdatecheck.outputs.needs-updating == 'true'

      - name: Build and push Docker images
        uses: docker/build-push-action@v2.6.1
        with:
          context: "${{ github.workspace }}"
          push: true
          tags: cryorig/caddycf:latest
        if: steps.baseupdatecheck.outputs.needs-updating == 'true'
